#### Link: https://ec.europa.eu/growth/tools-databases/cosing/
#### InciBeauty: https://incibeauty.com/ingredients/1

In [1]:
import camelot
import pandas as pd
import numpy as np

pdf_path = "Ingrediants_with_it\'s_usage.pdf"

tables = camelot.read_pdf(pdf_path, flavor="stream", pages="9-520")

In [2]:
ingrediants_df = pd.DataFrame()
for i in range(tables.n):
    ingrediants_df = pd.concat([ingrediants_df, tables[i].df[3:]], ignore_index=True)

In [3]:
ingrediants_df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
5       851
6      5619
7     10216
8     13898
9     14432
10    14485
dtype: int64

In [4]:
ingrediants_df

0  1  2           3                      4   \
0              ABIES BALSAMEA        85085-34-3              285-364-0   
1                     EXTRACT                                            
2             ABIES PECTINATA        92128-34-2              295-728-0   
3                     EXTRACT                                            
4         ABIES PECTINATA OIL        92128-34-2              295-728-0   
...                       ... .. ..         ...                    ...   
14534                 EXTRACT                                            
14535         ZIZYPHUS JUJUBA                    90045-99-1\n289-966-4   
14536                 EXTRACT                                            
14537  ZIZYPHUS SPINA CHRISTI                                            
14538                                                                    

                                                      5                   6   \
0      Abies Balsamea Extract\nis an extract of\nthe ...                       
1                                     balsamea, Pinaceae                       
2      Abies Pectinata Extract\nis an extract of\nthe...                       
3         of\nthe silver\nfir, Abies pectinata, Pinaceae                       
4      Abies Pectinata Oil\nis the volatile oil obtai...                       
...                                                  ...                 ...   
14534                      Zizyphus joazeiro, Rhamnaceae                       
14535  Zizyphus Jujuba Extract\nis an extract of\nthe...   Skin conditioning   
14536                jujube, Zizyphus jujuba, Rhamnaceae                       
14537  Ziziphus Spina Christi\nis the dried crushed l...  Skin conditioning’   
14538                 Zizyphus spina christi, Rhamnaceae                       

                                   7    8    9    10  
0      Film forming/hair conditioning  NaN  NaN  NaN  
1                                      NaN  NaN  NaN  
2                     Tonic/deodorant  NaN  NaN  NaN  
3                                      NaN  NaN  NaN  
4                       Tonic/masking  NaN  NaN  NaN  
...                               ...  ...  ...  ...  
14534                             NaN  NaN  NaN  NaN  
14535                             NaN  NaN  NaN  NaN  
14536                             NaN  NaN  NaN  NaN  
14537                             NaN  NaN  NaN  NaN  
14538                             NaN  NaN  NaN  NaN  

[14539 rows x 11 columns]

In [5]:
ingrediants_df.rename(columns = {0: "INCI name", 1: "INN name", 2: "Ph. Eur. Name", 3: "CAS No", 4: "EINECS/ELINCS No", 5: "Chem/IUPAC Name", 6: "Restriction", 7: "Function", 8:"Function_1", 9:"Function_2", 10:"Function_3"}, inplace=True)

In [6]:
ingrediants_df.Function.unique()

array(['Film forming/hair conditioning', '', 'Tonic/deodorant',
       'Tonic/masking', 'Emulsion stabilising', 'Viscosity controlling',
       'Hair dyeing/astringent', 'Skin conditioning', 'Tonic',
       'Viscosity controlling/astringent', 'the roots', 'the leaves of',
       'the bark and sap', 'Skin conditioning/emollient', 'Masking',
       'Buffering', 'Film forming/plasticiser',
       'Emollient/film forming/plasticiser',
       'Antioxidant/chelating/plasticiser', 'Tanning', 'Emollient',
       'Emollient/emulsion stabilising', 'Emollient/emulsifying',
       'Antistatic/emollient/emulsifying', 'Antistatic/emollient',
       'Antistatic/skin conditioning/hair', 'conditioning',
       'Soothing/antidandruff/refreshing/', 'cleansing/tonic', nan,
       'Skin conditioning/viscosity con-',
       'Skin conditioning/astringent/anti-', 'forming',
       'Skin conditioning/cleansing/astrin-', 'Emulsifying/surfactant',
       'Anticaking/emulsion stabilising',
       'Emulsion stabil

In [7]:
ingrediants_df.Function_1.unique()

array([nan, 'Soothing', '', 'Skin conditioning', 'Keratolytic',
       'Nail conditioning', 'Antistatic/humectant',
       'Antistatic/emollient/hair condition-', 'ing', 'Antistatic',
       'Stabilising', 'Antimicrobial', 'Buffering', 'Denaturant/solvent',
       'Hair dyeing', 'Antioxidant', 'Antistatic/hair conditioning',
       'Solvent', 'Surfactant', 'Emulsifying', 'Emollient', 'Humectant',
       'Abrasive/viscosity controlling', 'Emollient/solvent', 'Tonic',
       'Antioxidant/skin conditioning', 'ditioning/astringent/tonic',
       'Preservative/antistatic', 'Uv absorber', 'Preservative',
       'Film forming', 'Uv absorber/uv filter', 'Uv filter/uv absorber',
       'from', 'bovine animals aged', '12 months or ovine',
       'and caprine animals', 'tooth', 'erupted through the',
       'Antimicrobial/antistatic/deodorant/',
       'emulsifying/surfactant/hair condi-', 'tioning',
       'Emollient/skin protecting', 'Abrasive/absorbent/opacifying/visc-',
       'osity controll

In [8]:
ingrediants_df.Function_2.unique()

array([nan, '', 'Soothing/antiseborrhoeic/skin con-', 'VII/1,14',
       'VI/1,1', 'III/1,8', 'the', 'Humectant/plasticiser/skin condi-'],
      dtype=object)

In [9]:
ingrediants_df.Function_3.unique()

array([nan, 'Skin conditioning', '', 'Tonic/masking',
       'Emollient/tonic/masking', 'Stabilising', 'Emollient', 'Solvent',
       'Emollient/skin conditioning', 'Uv absorber/uv filter',
       'Propellant', 'Solvent/surfactant/viscosity con-', 'trolling',
       'Preservative/solvent', 'Antistatic/emollient/skin condi-',
       'tioning/hair conditioning', 'Emulsifying/emollient/solvent',
       'Emulsifying', 'Emollient/emulsion stabilising',
       'Viscosity controlling/emulsifying', 'Hair dyeing',
       'Emollient/skin conditioning/sooth-', 'ing',
       'Emollient/moisturising', 'Film forming/skin conditioning/',
       'hair conditioning', 'Antistatic/skin conditioning/hair',
       'conditioning'], dtype=object)

In [10]:
ingrediants_df.isnull().sum()

INCI name               0
INN name                0
Ph. Eur. Name           0
CAS No                  0
EINECS/ELINCS No        0
Chem/IUPAC Name       851
Restriction          5619
Function            10216
Function_1          13898
Function_2          14432
Function_3          14485
dtype: int64

In [11]:
data = {
  "Viscosity controlling": "Increases or decreases the viscosity of cosmetics",
  "Abrasive": "Removes materials from various body surfaces or aids mechanical tooth cleaning or improves gloss.",
  "Absorbent": "Takes up water- and/or oil-soluble dissolved or finely dispersed substances.",
  "Anticaking": "Allows free flow of solid particles and thus avoids agglomeration of powdered cosmetics into lumps or hard masses.",
  "Anticorrosive": "Prevents corrosion of the packaging.",
  "Antidandruff": "Helps control dandruff.",
  "Antifoaming": "Suppresses foam during manufacturing or reduces the tendency of finished products to generate foam.",
  "Antimicrobial": "Helps control the growth of micro-organisms on the skin.",
  "Antioxidant": "Inhibits reactions promoted by oxygen, thus avoiding oxidation and rancidity.",
  "Antiperspirant": "Reduces perspiration.",
  "Antiplaque": "Helps protect against plaque.",
  "Antiseborrhoeic": "Helps control sebum production.",
  "Antistatic": "Reduces static electricity by neutralising electrical charge on a surface.",
  "Astringent": "Contracts the skin.",
  "Binding": "Provides cohesion in cosmetics.",
  "Bleaching": "Lightens the shade of hair or skin.",
  "Buffering": "Stabilises the pH of cosmetics.",
  "Bulking": "Reduces bulk density of cosmetics.",
  "Chelating": "Reacts and forms complexes with metal ions which could affect the stability and/or appearance of cosmetics.",
  "Cleansing": "Helps to keep the body surface clean.",
  "Cosmetic colorant": "Colours cosmetics and/or imparts colour to the skin and/or its appendages. All colours listed are substances on the positive list of colorants (Annex IV to the Cosmetics Directive).",
  "Denaturant": "Renders cosmetics unpalatable. Mostly added to cosmetics containing ethyl alcohol.",
  "Deodorant": "Reduces or masks unpleasant body odours.",
  "Depilatory": "Removes unwanted body hair.",
  "Detangling": "Reduces or eliminates hair intertwining due to hair surface alteration or damage and, thus, helps combing.",
  "Emollient": "Softens and smooths the skin.",
  "Emulsifying": "Promotes the formation of intimate mixtures of non-miscible liquids by altering the interfacial tension.",
  "Emulsion stabilising": "Helps the process of emulsification and improves emulsion stability and shelf-life.",
  "Film forming": "Produces, upon application, a continuous film on skin, hair or nails.",
  "Foaming": "Traps numerous small bubbles of air or other gas within a small volume of liquid by modifying the surface tension of the liquid.",
  "Foam boosting": "Improves the quality of the foam produced by a system by increasing one or more of the following properties: volume, texture and/or stability.",
  "Gel forming": "Gives the consistency of a gel (a semi-solid preparation with some elasticity) to a liquid preparation.",
  "Hair conditioning": "Leaves the hair easy to comb, supple, soft and shiny and/or imparts volume, lightness, gloss, etc.",
  "Hair dyeing": "Colours hair.",
  "Hair fixing": "Permits physical control of hairstyle.",
  "Hair waving or straightening": "Modifies the chemical structure of the hair, allowing it to be set in the style required.",
  "Humectant": "Holds and retains moisture.",
  "Hydrotrope": "Enhances the solubility of substance which is only slightly soluble in water.",
  "Keratolytic": "Helps eliminate the dead cells of the stratum corneum.",
  "Masking": "Reduces or inhibits the basic odour or taste of the product.",
  "Moisturising": "Increases the water content of the skin and helps keep it soft and smooth.",
  "Nail conditioning": "Improves the cosmetic characteristics of the nail.",
  "Opacifying": "Reduces transparency or translucency of cosmetics.",
  "Oral care": "Provides cosmetic effects to the oral cavity, e.g. cleansing, deodorising, protecting.",
  "Oxidising": "Changes the chemical nature of another substance by adding oxygen or removing hydrogen.",
  "Pearlescent": "Imparts a nacreous appearance to cosmetics.",
  "Plasticiser": "Softens and makes supple another substance that otherwise could not be easily deformed, spread or worked out.",
  "Preservative": "Inhibits primarily the development of micro-organisms in cosmetics. All preservatives listed are substances on the positive list of preservatives (Annex VI to the cosmetics Directive).",
  "Propellant": "Generates pressure in an aerosol pack, expelling contents when the valve is opened. Some liquefied propellants can act as solvents.",
  "Reducing": "Changes the chemical nature of another substance by adding hydrogen or removing oxygen.",
  "Refatting": "Replenishes the lipids of the hair or of the top layers of the skin.",
  "Refreshing": "Imparts a pleasant freshness to the skin.",
  "Skin conditioning": "Maintains the skin in good condition.",
  "Skin protecting": "Helps to avoid harmful effects to the skin from external factors.",
  "Smoothing": "Seeks to achieve an even skin surface by decreasing roughness or irregularities.",
  "Solvent": "Dissolves other substances.",
  "Soothing": "Helps lightening discomfort of the skin or of the scalp.",
  "Stabilising": "Improves ingredients or formulation stability and shelf-life.",
  "Surfactant": "Lowers the surface tension of cosmetics as well as aids the even distribution of the product when used.",
  "Tanning": "Darkens the skin with or without exposure to UV.",
  "Tonic": "Produces a feeling of well-being on skin and hair.",
  "Uv absorber": "Protects the cosmetic product from the effects of UV light.",
  "Uv filter": "Filters certain UV rays in order to protect the skin or the hair from harmful effects of these rays. All UV filters listed are substances on the positive list of UV filters (Annex VII to the Cosmetics Directive)."
}

In [13]:
df = ingrediants_df.copy()

In [14]:
df.replace("", np.nan, inplace=True)

In [15]:
df.isnull().sum()

INCI name            2521
INN name            13962
Ph. Eur. Name       14234
CAS No               8927
EINECS/ELINCS No     7414
Chem/IUPAC Name      5918
Restriction         10610
Function            12085
Function_1          14211
Function_2          14531
Function_3          14499
dtype: int64

In [19]:
df.replace("", np.nan, inplace=True)

In [22]:
df.dropna(['Function'])

C:\Users\Dell\AppData\Local\Temp\ipykernel_18708\3677854618.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  df.dropna(['Function'])


TypeError: supplying multiple axes to axis is no longer supported.

In [23]:
df.shape

(14539, 11)

In [24]:
# for index, row in df_fun_nan.iterrows():
#         df.at[index, "Function"] = row["Function"]
#         df.at[index, "Restriction"] = np.nan 